### ISSUE TITLE
Node 10 can't find module worker_threads

### ISSUE THREAD

**Issue by herudi** [jkyberneees/low-http-server#8] opened 2021-01-04 02:28 UTC
Low http server is amazing based on uWS. . this is soo fast... but i'm try in node 10, i'm getting error  can't find module worker_threads. need --experimental-worker just can. Maybe [https://github.com/jkyberneees/low-http-server/blob/master/src/utils/os-compat-check.js](https://github.com/jkyberneees/low-http-server/blob/master/src/utils/os-compat-check.js).

Thanks ...

**Comment by schamberg97** [comment] 2021-03-15 10:31
You are indeed correct in identifying the issue, I'll fix it today. However, I am not certain I can `npm publish` the new version

**Comment by schamberg97** [comment] 2021-03-15 10:44
@herudi the issue is fixed in the `master` branch, however, I do not have the permissions to publish. Perhaps @jkyberneees could do it later? Meanwhile, you can get the package directly from git

**Comment by jkyberneees** [comment] 2021-03-15 10:48
Thanks @schamberg97 will review and release ASAP

**Comment by schamberg97** [comment] 2021-03-15 11:56
@jkyberneees don't rush, there are some more changes

**Comment by jkyberneees** [comment] 2021-03-15 18:19
Hi @schamberg97 @herudi, fix is now available in v2.1.2

Great work @schamberg97!

**Comment by jkyberneees** [comment] 2021-03-15 18:20
> @jkyberneees don't rush, there are some more changes coming. Also, perhaps it would make sense to grant me the ability to `npm publish` at some later stage, if you are comfortable with it, so I can deal with the more trivial of issues.

Hey @schamberg97 sounds great, could you please drop me an email: kyberneees@gmail.com ?

**Closed** 2021-03-15 18:20 UTC

**Comment by herudi** [comment] 2021-03-16 00:51
@jkyberneees @schamberg97 so great ... thanks for fixing my problem...
